name: Weekly Deploy
on:
  push:
    branches:
      - master # default branch
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      # check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build

      - name: Set up environment
        env:
          HOST: ${{ secrets.SCP_HOST }}
          PORT: ${{ secrets.SCP_PORT }}
          USERNAME: ${{ secrets.SCP_USERNAME }}
          PASSWORD: ${{ secrets.SCP_PASSWORD }}
        run: echo "Set up environment variables"

      - name:  deploy file to server
        run: |
          scp -P {{env.PORT}} -r GITHUB_WORKSPACE/public/* {{env.USERNAME}}@{{env.HOST}}:/var/www/weekly/

