name: Weekly Deploy
on:
  push:
    branches:
      - master # default branch
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      # check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build

      - name: deploy file to server
        uses: zkep/SFTP-Deploy-Action@master
        with:
          username: 'root'
          server: ${{ secrets.SERVER_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './public/*'
          remote_path: '/var/www/weekly/'
